/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AIS;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Chandan
 */
public class Chat extends javax.swing.JFrame  {
    /**
     * Creates new form Chat
     */
    String Name="You";
    public Chat() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textbox = new javax.swing.JTextArea();
        colorpanel = new javax.swing.JPanel();
        loading = new javax.swing.JProgressBar();
        progressl = new javax.swing.JLabel();
        listenbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        editablec = new javax.swing.JCheckBox();
        speakbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sendbtn = new javax.swing.JButton();
        sendtf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FunBox");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        textbox.setEditable(false);
        textbox.setColumns(20);
        textbox.setFont(new java.awt.Font("SimSun-ExtB", 3, 13)); // NOI18N
        textbox.setRows(5);
        textbox.setToolTipText("");
        textbox.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        jScrollPane1.setViewportView(textbox);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 430, 420);

        colorpanel.setBackground(new java.awt.Color(0, 0, 153));

        loading.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        listenbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voic.png"))); // NOI18N
        listenbtn.setToolTipText("speak");

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        editablec.setText("Editable Box");
        editablec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editablecActionPerformed(evt);
            }
        });

        speakbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/speakF.png"))); // NOI18N
        speakbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setText("Change Name!");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 0, 0)));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        sendbtn.setText("Send");
        sendbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendbtnMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sendbtnMouseReleased(evt);
            }
        });
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });
        sendbtn.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                sendbtnVetoableChange(evt);
            }
        });

        sendtf.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        sendtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendtfMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendtfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendtfMouseExited(evt);
            }
        });
        sendtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtfActionPerformed(evt);
            }
        });
        sendtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sendtfKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout colorpanelLayout = new javax.swing.GroupLayout(colorpanel);
        colorpanel.setLayout(colorpanelLayout);
        colorpanelLayout.setHorizontalGroup(
            colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(colorpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(colorpanelLayout.createSequentialGroup()
                        .addComponent(editablec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(209, Short.MAX_VALUE))
                    .addGroup(colorpanelLayout.createSequentialGroup()
                        .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorpanelLayout.createSequentialGroup()
                                .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(progressl, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sendtf, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(colorpanelLayout.createSequentialGroup()
                                .addComponent(listenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(speakbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sendbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        colorpanelLayout.setVerticalGroup(
            colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(colorpanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorpanelLayout.createSequentialGroup()
                        .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(progressl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loading, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(editablec))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorpanelLayout.createSequentialGroup()
                        .addGroup(colorpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearbtn)
                            .addComponent(speakbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(colorpanel);
        colorpanel.setBounds(0, 420, 450, 140);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 560));

        getAccessibleContext().setAccessibleName("Funbox");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
       String msg;
       String old;
       String setmsg;
       
       try{
       msg = sendtf.getText();
       if(!msg.isEmpty())
       { 
         old = textbox.getText();
         loading.setValue(50);
         progressl.setText("Sent");
         textbox.setText(old+"\n"+Name+":"+msg);
         sendtf.setText("");
         old=textbox.getText();
        
        
             setmsg=new WhatSay().Decide(msg,Name);
             loading.setValue(100);     
             textbox.setText( old +"\n"+ "AIS"+":"+setmsg);
       } }catch(Exception e){JOptionPane.showMessageDialog(null,"SomeThing Went Wrong,Process Interrupted!!\n"+e.getMessage());}
       
       
       
       
        
        
    }//GEN-LAST:event_sendbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
     textbox.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_clearbtnActionPerformed

    private void editablecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editablecActionPerformed
       textbox.setEditable(true);
        sendbtn.setEnabled(false);
       if(!editablec.isSelected())
       {   sendbtn.setEnabled(true);
           textbox.setEditable(false);}
    }//GEN-LAST:event_editablecActionPerformed

    private void speakbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakbtnActionPerformed
      String msgT=textbox.getText();
      if(!msgT.isEmpty())
          new ReturnVoice(msgT);
      else{   textbox.setText("AIS:Enter Any Line Or Word As Text....");
      new ReturnVoice("Enter Any Line Or Word As Text");}
     
     
     
     
    }//GEN-LAST:event_speakbtnActionPerformed

    private void sendbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendbtnMouseReleased
      
    }//GEN-LAST:event_sendbtnMouseReleased

    private void sendbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendbtnMouseExited
         loading.setValue(0);
         progressl.setText("");         // TODO add your handling code here:
    }//GEN-LAST:event_sendbtnMouseExited

    private void sendtfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendtfMouseEntered
       
         progressl.setText("Typing..");         // TODO add your handling code here:
    }//GEN-LAST:event_sendtfMouseEntered

    private void sendtfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendtfMouseExited

         progressl.setText("");         // removing "typing" from label progress1.....
    }//GEN-LAST:event_sendtfMouseExited

    private void sendbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendbtnMouseClicked
       
       
    }//GEN-LAST:event_sendbtnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    Name=JOptionPane.showInputDialog("Enter Your Name Before Chat For Better FeedBack..");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void sendtfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendtfMouseClicked
       progressl.setText("Typing...");
    }//GEN-LAST:event_sendtfMouseClicked

    private void sendtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sendtfKeyPressed
       
    }//GEN-LAST:event_sendtfKeyPressed

    private void sendbtnVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_sendbtnVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sendbtnVetoableChange

    private void sendtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtfActionPerformed
         sendbtnActionPerformed(null);        
    }//GEN-LAST:event_sendtfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Chat().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JPanel colorpanel;
    private javax.swing.JCheckBox editablec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listenbtn;
    private javax.swing.JProgressBar loading;
    private javax.swing.JLabel progressl;
    private javax.swing.JButton sendbtn;
    private javax.swing.JTextField sendtf;
    private javax.swing.JButton speakbtn;
    private javax.swing.JTextArea textbox;
    // End of variables declaration//GEN-END:variables
}
