/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AIS;

import java.io.IOException;
import java.net.URISyntaxException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chandan
 */
public class InterFace extends javax.swing.JFrame {

    /**
     * Creates new form InterFace
     */
   String A;
   
   
   
   
   char[] passW;
   
   public final void setLogout(){
        chatbtn.setEnabled(false);
        cmdbtn.setEnabled(false);
        voicebtn.setEnabled(false);
        passoutbtn.setEnabled(false);
        passf.setEnabled(true);
        passl.setEnabled(true);
        passbtn.setEnabled(true);
   }
   public void setLogin(){
        chatbtn.setEnabled(true);
        cmdbtn.setEnabled(true);       
        voicebtn.setEnabled(true);
        passbtn.setEnabled(false);
        passf.setText("");
        passf.setEnabled(false);
        passl.setEnabled(false);
        passoutbtn.setEnabled(true);
   }
   public void Loginbtn(){
       /*******************
        Password checking
       *******************/
        
       A=new OldPass().old();
        String pass1 = new String(passf.getPassword()); 
        String pass;
        pass = pass1.toUpperCase();
        if(pass.isEmpty()){
        JOptionPane.showMessageDialog(null,"Enter The Password before Login...");
        }        
        if(pass.equalsIgnoreCase(A)){
        JOptionPane.showMessageDialog(null,"Sucess!! Welcome to KARL-AIS.. ");
        setLogin();
        }
        if(!pass.equalsIgnoreCase(A)&&!pass.isEmpty()){
        JOptionPane.showMessageDialog(null,"Access Denied Error 0012='Wrong PassWord' ");
        }   
        /**********************************************************************************
        ***********************************************************************************/
   
   }
   
   
   
   public InterFace() {
        initComponents();
        setLogout();
                                                           // Date and Time Thread
   Thread Clockthread=new Thread(){
       @Override
   public void run(){ try{
            
            
            DateFormat df=new SimpleDateFormat("hh:mm:ss dd/MM/yyyy");
            while(true){
            
            Date d=new Date();
            String dt=df.format(d);
            date.setText(dt);
            sleep(1000);}
        }catch(InterruptedException e){JOptionPane.showMessageDialog(null,e.getMessage());}}};    
   
   Clockthread.start();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Popup = new javax.swing.JPopupMenu();
        Refresh = new javax.swing.JMenuItem();
        Shutdown = new javax.swing.JMenuItem();
        Restart = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        voicebtn = new javax.swing.JButton();
        chatbtn = new javax.swing.JButton();
        info = new javax.swing.JButton();
        cmdbtn = new javax.swing.JButton();
        passl = new javax.swing.JLabel();
        passf = new javax.swing.JPasswordField();
        passbtn = new javax.swing.JButton();
        passoutbtn = new javax.swing.JButton();
        mpbtn = new javax.swing.JButton();
        ytbtn = new javax.swing.JButton();
        powerbtn = new javax.swing.JButton();
        searchl = new javax.swing.JLabel();
        Searchf = new javax.swing.JTextField();
        setting = new javax.swing.JButton();
        resetp = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Alarm = new javax.swing.JButton();
        imagelbl = new javax.swing.JLabel();

        Popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PopupMouseReleased(evt);
            }
        });

        Refresh.setText("jMenuItem1");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        Shutdown.setText("jMenuItem2");

        Restart.setText("jMenuItem3");

        About.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KARL AIS - Assist is Simple");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setLayout(null);

        voicebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voic.png"))); // NOI18N
        voicebtn.setToolTipText("Voice Command");
        voicebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.red));
        jPanel1.add(voicebtn);
        voicebtn.setBounds(750, 330, 30, 40);

        chatbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ChatF.png"))); // NOI18N
        chatbtn.setToolTipText("Assistant chatbox");
        chatbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.red));
        chatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatbtnActionPerformed(evt);
            }
        });
        jPanel1.add(chatbtn);
        chatbtn.setBounds(70, 340, 38, 35);

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon.png"))); // NOI18N
        info.setToolTipText("info");
        info.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.red, java.awt.Color.blue));
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        jPanel1.add(info);
        info.setBounds(800, 330, 40, 40);

        cmdbtn.setBackground(new java.awt.Color(255, 255, 255));
        cmdbtn.setForeground(new java.awt.Color(102, 153, 255));
        cmdbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/keyboard.png"))); // NOI18N
        cmdbtn.setToolTipText("Enter Command");
        cmdbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.black, java.awt.Color.red, java.awt.Color.blue));
        cmdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbtnActionPerformed(evt);
            }
        });
        jPanel1.add(cmdbtn);
        cmdbtn.setBounds(10, 340, 45, 35);

        passl.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        passl.setForeground(new java.awt.Color(255, 255, 255));
        passl.setText("PASSWORD");
        passl.setToolTipText("passwordReqiured");
        passl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(passl);
        passl.setBounds(350, 340, 70, 25);

        passf.setToolTipText("Enter password");
        passf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfActionPerformed(evt);
            }
        });
        passf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passfKeyPressed(evt);
            }
        });
        jPanel1.add(passf);
        passf.setBounds(430, 340, 200, 23);

        passbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginbtnF .png"))); // NOI18N
        passbtn.setToolTipText("login");
        passbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.red));
        passbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passbtnActionPerformed(evt);
            }
        });
        jPanel1.add(passbtn);
        passbtn.setBounds(650, 335, 30, 30);

        passoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lgout .png"))); // NOI18N
        passoutbtn.setToolTipText("logout");
        passoutbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.red, java.awt.Color.blue));
        passoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(passoutbtn);
        passoutbtn.setBounds(690, 335, 30, 30);

        mpbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playM.png"))); // NOI18N
        mpbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.red, java.awt.Color.blue));
        mpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(mpbtn);
        mpbtn.setBounds(120, 340, 38, 35);

        ytbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ytbtn.png"))); // NOI18N
        ytbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), null, new java.awt.Color(51, 0, 255), new java.awt.Color(255, 0, 51)));
        ytbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytbtnActionPerformed(evt);
            }
        });
        jPanel1.add(ytbtn);
        ytbtn.setBounds(170, 340, 38, 35);

        powerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pwr123.png"))); // NOI18N
        powerbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.red));
        powerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(powerbtn);
        powerbtn.setBounds(860, 330, 40, 40);

        searchl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/web.png"))); // NOI18N
        searchl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlMouseClicked(evt);
            }
        });
        jPanel1.add(searchl);
        searchl.setBounds(198, 82, 20, 20);

        Searchf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Searchf.setToolTipText("");
        Searchf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Searchf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Searchf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchfActionPerformed(evt);
            }
        });
        jPanel1.add(Searchf);
        Searchf.setBounds(20, 80, 200, 25);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Setting.png"))); // NOI18N
        setting.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.blue));
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });
        jPanel1.add(setting);
        setting.setBounds(220, 78, 30, 29);

        resetp.setForeground(new java.awt.Color(255, 255, 255));
        resetp.setText("Manage Password !");
        resetp.setToolTipText("Click it");
        resetp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetpMouseClicked(evt);
            }
        });
        jPanel1.add(resetp);
        resetp.setBounds(520, 370, 120, 14);

        version.setForeground(new java.awt.Color(255, 255, 255));
        version.setText(" Beta 1.0 version 0.5.1 ");
        version.setToolTipText("Rks Pvt Ltd.");
        version.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                versionMouseEntered(evt);
            }
        });
        jPanel1.add(version);
        version.setBounds(740, 380, 150, 20);

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date and Time");
        date.setToolTipText("");
        date.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, new java.awt.Color(0, 0, 255), new java.awt.Color(255, 0, 102)));
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dateMouseExited(evt);
            }
        });
        jPanel1.add(date);
        date.setBounds(20, 30, 180, 30);

        Alarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Alarm.png"))); // NOI18N
        Alarm.setToolTipText("Reminder");
        Alarm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.white, java.awt.Color.red, java.awt.Color.blue));
        Alarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlarmActionPerformed(evt);
            }
        });
        jPanel1.add(Alarm);
        Alarm.setBounds(210, 28, 32, 32);

        imagelbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/interfaceF.png"))); // NOI18N
        imagelbl.setToolTipText("");
        jPanel1.add(imagelbl);
        imagelbl.setBounds(0, 0, 920, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("AIS - Assist is Simple");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbtnActionPerformed
        getCmd cmdprompt=new getCmd(); 
        cmdprompt.setVisible(true);
    }//GEN-LAST:event_cmdbtnActionPerformed

    private void passbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passbtnActionPerformed
       Loginbtn();
    }//GEN-LAST:event_passbtnActionPerformed

    private void passoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passoutbtnActionPerformed
       
       int a=JOptionPane.showConfirmDialog(rootPane, "Are You Sure to Logout");
       try{
           if(JOptionPane.YES_OPTION==a){
            setLogout();
         } 
       }catch(Exception e){
       JOptionPane.showConfirmDialog(rootPane, "Oops SomeThing Went Wrong!!!");
       System.exit(0);
       }                       
        
    }//GEN-LAST:event_passoutbtnActionPerformed

    private void chatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatbtnActionPerformed
       
           Chat ch=new Chat();
           ch.setVisible(true);
       
       
    }//GEN-LAST:event_chatbtnActionPerformed

    private void resetpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetpMouseClicked
       try{
        new ResetPassword().setVisible(true);
       }catch(IOException ev){}     
    }//GEN-LAST:event_resetpMouseClicked

    private void passfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passfKeyPressed
       
    }//GEN-LAST:event_passfKeyPressed

    private void versionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_versionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_versionMouseEntered

    private void mpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpbtnActionPerformed
           try {
            Runtime.getRuntime().exec("vlc");
       } catch (IOException ex) {
           Logger.getLogger(InterFace.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_mpbtnActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
       new Infoframe().setVisible(true);
    }//GEN-LAST:event_infoActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshActionPerformed

    private void PopupMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopupMouseReleased
       
    
    }//GEN-LAST:event_PopupMouseReleased

    private void powerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerbtnActionPerformed
       PowerDialog powerDialog = new PowerDialog(null,true);
       powerDialog.setVisible(true);
    }//GEN-LAST:event_powerbtnActionPerformed

    private void SearchfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchfActionPerformed
           
           String searchbox=Searchf.getText().replace(" ","+");
           String link="https://www.google.co.in/webhp?hl=en&sa=X&ved=0ahUKEwiqgPD7kL3UAhVBqY8KHV9xBKEQPAgD#hl=en&q="+searchbox;
           
          
       try {
            new OpenUrl().open(link);
            new ReturnVoice(Searchf.getText());
       } catch (URISyntaxException ex) {
           Logger.getLogger(InterFace.class.getName()).log(Level.SEVERE, null, ex);
       }
          
                                            
    }//GEN-LAST:event_SearchfActionPerformed

    private void ytbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytbtnActionPerformed
       try{String msg=new WhatSay().Decide("site youtube",null);}catch(IOException | URISyntaxException e){}
    }//GEN-LAST:event_ytbtnActionPerformed

    private void passfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfActionPerformed
       passbtnActionPerformed(null);
    }//GEN-LAST:event_passfActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
      
       
    }//GEN-LAST:event_settingActionPerformed

    private void dateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseExited
        
    }//GEN-LAST:event_dateMouseExited

    private void dateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMouseEntered

    }//GEN-LAST:event_dateMouseEntered

    private void AlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlarmActionPerformed
      new SetAlarm(null,true).setVisible(true);
    }//GEN-LAST:event_AlarmActionPerformed

    private void searchlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlMouseClicked
        SearchfActionPerformed(null);
    }//GEN-LAST:event_searchlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterFace().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton Alarm;
    private javax.swing.JPopupMenu Popup;
    private javax.swing.JMenuItem Refresh;
    private javax.swing.JMenuItem Restart;
    private javax.swing.JTextField Searchf;
    private javax.swing.JMenuItem Shutdown;
    private javax.swing.JButton chatbtn;
    private javax.swing.JButton cmdbtn;
    private javax.swing.JLabel date;
    private javax.swing.JLabel imagelbl;
    private javax.swing.JButton info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mpbtn;
    private javax.swing.JButton passbtn;
    private javax.swing.JPasswordField passf;
    private javax.swing.JLabel passl;
    private javax.swing.JButton passoutbtn;
    private javax.swing.JButton powerbtn;
    private javax.swing.JLabel resetp;
    private javax.swing.JLabel searchl;
    private javax.swing.JButton setting;
    private javax.swing.JLabel version;
    private javax.swing.JButton voicebtn;
    private javax.swing.JButton ytbtn;
    // End of variables declaration//GEN-END:variables
}
