/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AIS;

import java.util.Arrays;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chandan
 */
public class ResetPassword extends javax.swing.JFrame {
String OTP=new String();
String newpass;
String oldp;
int rmni;

String ei=new String();
String rmn=new String();
String np=new String();
String cp=new String();
String op=new String();
String np1=new String();
String cp1=new String();
/**
     * Creates new form ResetPassword
     * @throws java.io.IOException
     */
    public ResetPassword() throws IOException {
    initComponents();
    
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        cpp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opf = new javax.swing.JPasswordField();
        npf1 = new javax.swing.JPasswordField();
        cpf1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        fpp = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mnc = new javax.swing.JCheckBox();
        eic = new javax.swing.JCheckBox();
        resetbtn = new javax.swing.JButton();
        cpf = new javax.swing.JTextField();
        cpl = new javax.swing.JLabel();
        npl = new javax.swing.JLabel();
        npf = new javax.swing.JTextField();
        eil = new javax.swing.JLabel();
        eif = new javax.swing.JTextField();
        rmnl = new javax.swing.JLabel();
        rmnf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reset Password");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        cpp.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password");
        cpp.add(jLabel2);
        jLabel2.setBounds(70, 260, 100, 20);

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Old Password");
        cpp.add(jLabel3);
        jLabel3.setBounds(70, 120, 100, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        cpp.add(jLabel4);
        jLabel4.setBounds(70, 190, 100, 20);
        cpp.add(opf);
        opf.setBounds(220, 120, 160, 25);
        cpp.add(npf1);
        npf1.setBounds(220, 190, 160, 25);
        cpp.add(cpf1);
        cpf1.setBounds(220, 260, 160, 25);

        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        cpp.add(jButton1);
        jButton1.setBounds(150, 370, 130, 30);

        jLabel5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cpasswordkey.png"))); // NOI18N
        jLabel5.setText("         FILL THE REQUIRED INFORMATION");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cpp.add(jLabel5);
        jLabel5.setBounds(30, 10, 380, 70);
        cpp.add(jDesktopPane2);
        jDesktopPane2.setBounds(-1, -1, 450, 500);

        jTabbedPane1.addTab("Change Password", cpp);

        fpp.setLayout(null);

        mnc.setBackground(new java.awt.Color(255, 51, 102));
        mnc.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        mnc.setForeground(new java.awt.Color(255, 255, 255));
        mnc.setText("Mobile No");
        mnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mncActionPerformed(evt);
            }
        });
        jDesktopPane1.add(mnc);
        mnc.setBounds(50, 350, 100, 20);

        eic.setBackground(new java.awt.Color(255, 0, 102));
        eic.setFont(new java.awt.Font("Verdana", 3, 11)); // NOI18N
        eic.setForeground(new java.awt.Color(255, 255, 255));
        eic.setText("Email id");
        eic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eicActionPerformed(evt);
            }
        });
        jDesktopPane1.add(eic);
        eic.setBounds(270, 350, 100, 20);

        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        jDesktopPane1.add(resetbtn);
        resetbtn.setBounds(150, 410, 120, 30);
        jDesktopPane1.add(cpf);
        cpf.setBounds(220, 270, 170, 25);

        cpl.setBackground(new java.awt.Color(255, 255, 255));
        cpl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cpl.setForeground(new java.awt.Color(255, 255, 255));
        cpl.setText("Confirm Password");
        jDesktopPane1.add(cpl);
        cpl.setBounds(40, 270, 140, 20);

        npl.setBackground(new java.awt.Color(255, 255, 255));
        npl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        npl.setForeground(new java.awt.Color(255, 255, 255));
        npl.setText("New Password");
        jDesktopPane1.add(npl);
        npl.setBounds(40, 210, 140, 20);

        npf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npfActionPerformed(evt);
            }
        });
        jDesktopPane1.add(npf);
        npf.setBounds(220, 210, 170, 25);

        eil.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        eil.setForeground(new java.awt.Color(255, 255, 255));
        eil.setText("Email id");
        jDesktopPane1.add(eil);
        eil.setBounds(40, 150, 130, 20);

        eif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eifActionPerformed(evt);
            }
        });
        jDesktopPane1.add(eif);
        eif.setBounds(220, 150, 170, 25);

        rmnl.setBackground(new java.awt.Color(255, 255, 255));
        rmnl.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        rmnl.setForeground(new java.awt.Color(255, 255, 255));
        rmnl.setText("Reg. Mobile No.");
        jDesktopPane1.add(rmnl);
        rmnl.setBounds(40, 90, 140, 20);

        rmnf.setText("Not WorkingYet");
        rmnf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmnfActionPerformed(evt);
            }
        });
        jDesktopPane1.add(rmnf);
        rmnf.setBounds(220, 90, 170, 25);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" RESET YOUR PASSWORD BY FILLING BLOCKS GIVEN BELOW ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(40, 20, 370, 30);

        fpp.add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 450, 500);

        jTabbedPane1.addTab("Forgot Password", fpp);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 450, 520);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void npfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npfActionPerformed

    private void eifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eifActionPerformed

    private void eicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eicActionPerformed
         if(mnc.isSelected()){
             mnc.setSelected(false);
      }
    }//GEN-LAST:event_eicActionPerformed

    private void mncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mncActionPerformed
      
        if(eic.isSelected()){
        eic.setSelected(false);
      
      }
    }//GEN-LAST:event_mncActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        rmn=rmnf.getText();
       
        rmni=Integer.parseInt(rmn);
        ei=eif.getText();
        np=npf.getText();
        cp=cpf.getText();
       
           if(cp.isEmpty()||np.isEmpty()||ei.isEmpty()||rmn.isEmpty())             
     
           {
               JOptionPane.showMessageDialog(null,"Fill All the Required Information");
              
           }
       
          else
           { 
         
        if(mnc.isSelected()||eic.isSelected())
         {    if(np.equals(cp))
              {
               OTP =JOptionPane.showInputDialog(rootPane, "Enter Your OTP","OTP SENT", HEIGHT);
              }
         
             else
             {
             JOptionPane.showMessageDialog(null,"Password don't Matching");
             }
         
         }
         
        else{
            JOptionPane.showMessageDialog(rootPane,"Choose The Way To Get OTP");
           }
         
         }
       
       
        
    }//GEN-LAST:event_resetbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         
         op=Arrays.toString(opf.getPassword()).replace(", ","").replace("[","").replace("]","").trim();
         np1 = Arrays.toString(npf1.getPassword()).replace(", ","").replace("[","").replace("]","").trim();
        
         cp1 = Arrays.toString(cpf1.getPassword()).replace(", ","").replace("[","").replace("]","").trim();
         int a=np1.length(); 
         int b=op.length();
         
         
              oldp=new OldPass().old();
           
                System.out.println(np1 + cp1 + a +","+ b +","+oldp);
                if((a==0)||(b==0))             
                {
                    JOptionPane.showMessageDialog(null,"Fill All the Information before proceed");
                }
                
               else {
                             if(np1.equalsIgnoreCase(cp1)){   
                                     if(op.equalsIgnoreCase(oldp)){
                                                         try {
                                                          new Reset().change(Arrays.toString(npf1.getPassword()).replace(", ","").replace("[","").replace("]","").trim());
                                                         } catch (IOException ex) {
                                                         Logger.getLogger(ResetPassword.class.getName()).log(Level.SEVERE, null, ex);
                                                             }
                                                         System.out.println("rp,op,oldp ok");
                                                         JOptionPane.showMessageDialog(null,"Your PassWord is Now Changed");
                                     setVisible(false);
                                     dispose();
                                     }
                              else
                              JOptionPane.showMessageDialog(null,"Password don't Matched,Try Again");
           
           }
       
                }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rmnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmnfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmnfActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ResetPassword().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(ResetPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpf;
    private javax.swing.JPasswordField cpf1;
    private javax.swing.JLabel cpl;
    private javax.swing.JPanel cpp;
    private javax.swing.JCheckBox eic;
    private javax.swing.JTextField eif;
    private javax.swing.JLabel eil;
    private javax.swing.JPanel fpp;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox mnc;
    private javax.swing.JTextField npf;
    private javax.swing.JPasswordField npf1;
    private javax.swing.JLabel npl;
    private javax.swing.JPasswordField opf;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField rmnf;
    private javax.swing.JLabel rmnl;
    // End of variables declaration//GEN-END:variables
}
