/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AIS;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Chandan
 */


public class SetAlarm extends javax.swing.JDialog {

    /**
     * Creates new form SetAlarm
     */
   
   private int hour;
   private int minute;
   private int second;
   private Calendar calendar;
   private int Alarm_hour; 
   private int Alarm_minute; 
  
   
   
   
   
 
    
   
   
   Thread CurrentTime=new Thread(){
    @Override
    
    public void run(){
    while(true){
    calendar=new GregorianCalendar();
    hour=calendar.get(Calendar.HOUR);
    minute=calendar.get(Calendar.MINUTE);
    second=calendar.get(Calendar.SECOND);
    Current_T.setText("Time "+hour+":"+minute+":"+second);
   
    }
    }
    };
    
    
  
   
   public SetAlarm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Am_Rb.setSelected(modal);
        CurrentTime.start();
     
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Increase = new javax.swing.JButton();
        Decrease = new javax.swing.JButton();
        Increase2 = new javax.swing.JButton();
        Decrease2 = new javax.swing.JButton();
        Am_Rb = new javax.swing.JRadioButton();
        Pm_Rb = new javax.swing.JRadioButton();
        Hour_Tb = new javax.swing.JTextField();
        Minute_Tb = new javax.swing.JTextField();
        Alarmpng = new javax.swing.JLabel();
        HourL = new javax.swing.JLabel();
        MinuteL = new javax.swing.JLabel();
        Alarm_Set = new javax.swing.JButton();
        Current_T = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        Increase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/up.png"))); // NOI18N
        Increase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseActionPerformed(evt);
            }
        });

        Decrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/down.001.jpg.png"))); // NOI18N
        Decrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseActionPerformed(evt);
            }
        });

        Increase2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/up.png"))); // NOI18N
        Increase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Increase2ActionPerformed(evt);
            }
        });

        Decrease2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/down.001.jpg.png"))); // NOI18N
        Decrease2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Decrease2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Am_Rb);
        Am_Rb.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Am_Rb.setText("AM");
        Am_Rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Am_RbActionPerformed(evt);
            }
        });

        buttonGroup1.add(Pm_Rb);
        Pm_Rb.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Pm_Rb.setText("PM");
        Pm_Rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pm_RbActionPerformed(evt);
            }
        });

        Hour_Tb.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Hour_Tb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hour_Tb.setText("00");
        Hour_Tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Hour_TbMouseClicked(evt);
            }
        });
        Hour_Tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hour_TbActionPerformed(evt);
            }
        });

        Minute_Tb.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        Minute_Tb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Minute_Tb.setText("00");
        Minute_Tb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Minute_TbActionPerformed(evt);
            }
        });

        Alarmpng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CLockD.png"))); // NOI18N

        HourL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        HourL.setText("Hours");

        MinuteL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        MinuteL.setText("Minutes");

        Alarm_Set.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Alarm_Set.setText("SET");
        Alarm_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alarm_SetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Alarmpng, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Increase, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Decrease, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(Hour_Tb, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HourL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Decrease2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Minute_Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Increase2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinuteL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pm_Rb)
                            .addComponent(Am_Rb)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Current_T, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Alarm_Set, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Alarmpng)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Current_T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Increase, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Hour_Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HourL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Decrease, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Increase2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Am_Rb))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pm_Rb)
                                            .addComponent(Minute_Tb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(MinuteL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Decrease2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(Alarm_Set)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        Am_Rb.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseActionPerformed
         Inc_Dcr('I','H');  
    }//GEN-LAST:event_IncreaseActionPerformed

    private void DecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseActionPerformed
      Inc_Dcr('D','H'); 
    }//GEN-LAST:event_DecreaseActionPerformed

    private void Increase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Increase2ActionPerformed
         Inc_Dcr('I','M'); 
    }//GEN-LAST:event_Increase2ActionPerformed

    private void Decrease2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Decrease2ActionPerformed
         Inc_Dcr('D','M');
    }//GEN-LAST:event_Decrease2ActionPerformed

    private void Minute_TbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Minute_TbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Minute_TbActionPerformed

    private void Hour_TbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hour_TbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hour_TbActionPerformed

    private void Am_RbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Am_RbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Am_RbActionPerformed

    private void Pm_RbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pm_RbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pm_RbActionPerformed

    private void Hour_TbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hour_TbMouseClicked
        
    }//GEN-LAST:event_Hour_TbMouseClicked

    private void Alarm_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alarm_SetActionPerformed
      setAlarm();
    }//GEN-LAST:event_Alarm_SetActionPerformed

    private void setAlarm(){
    
    
    
    
    
    
    
    
    
    
    
    
    }
    
    
    
    
    
    
    
    
    
    private void Inc_Dcr(char inc_dcr,char H_M){
     
       Alarm_hour=Integer.parseInt(Hour_Tb.getText());
       Alarm_minute=Integer.parseInt(Minute_Tb.getText());
                             if((H_M=='H')&&(inc_dcr=='I'))
                              {
                                 if(Alarm_hour==12) Alarm_hour=0;
                                                   
                               Hour_Tb.setText(String.format("%02d",(Alarm_hour+1)));
                              
                              }
                              if((H_M=='H')&&(inc_dcr=='D'))                     //Hours
                               { 
                                 if(Alarm_hour==1) Alarm_hour=13;    
                                Hour_Tb.setText(String.format("%02d",(Alarm_hour-1)));
                               }
                                          
            

                             if((H_M=='M')&&(inc_dcr=='I'))    
                              {  if(Alarm_minute==60) Alarm_minute=-1;
                              Minute_Tb.setText(String.format("%02d",(Alarm_minute+1)));
                              }
    
                             if((H_M=='M')&&(inc_dcr=='D'))    
                             {  if(Alarm_minute==0) Alarm_minute=61;
                             Minute_Tb.setText(String.format("%02d",(Alarm_minute-1)));
                             }
                                           
    }
    
    
   
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetAlarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            SetAlarm dialog = new SetAlarm(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
               
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
            
        });
        
    }
  
    
    
    
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alarm_Set;
    private javax.swing.JLabel Alarmpng;
    private javax.swing.JRadioButton Am_Rb;
    private javax.swing.JLabel Current_T;
    private javax.swing.JButton Decrease;
    private javax.swing.JButton Decrease2;
    private javax.swing.JLabel HourL;
    private javax.swing.JTextField Hour_Tb;
    private javax.swing.JButton Increase;
    private javax.swing.JButton Increase2;
    private javax.swing.JLabel MinuteL;
    private javax.swing.JTextField Minute_Tb;
    private javax.swing.JRadioButton Pm_Rb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}



